### PR TITLE
Create tower of hanoi.cpp

### PR DESCRIPTION
**Pull request by bvsslgayathri-8679**
tower of hanoi in cpp

### CODE REVIEW

**Comment by Sumitsah5** [comment]
Hey, Can i code on this project

**Comment by Sumitsah5** [comment]
Hey, i have code this project as 
[21.+Tower+of+Hanoi.pdf](https://github.com/Sushreesatarupa/DSA-cpp-Hacktoberfest2021/files/7252577/21.%2BTower%2Bof%2BHanoi.pdf)
can you please add and merge.

**Comment by Sushreesatarupa** [comment]
> tower of hanoi in cpp

Your pr is merged! If you want your prs to be counted for hacktoberfest, you have to wait till October 1 to send pr :D

**Comment by Sushreesatarupa** [comment]
> Hey, i have code this project as [21.+Tower+of+Hanoi.pdf](https://github.com/Sushreesatarupa/DSA-cpp-Hacktoberfest2021/files/7252577/21.%2BTower%2Bof%2BHanoi.pdf) can you please add and merge.

Can you send a pull request for the same ? You can use TXT file for an algorithm with a nomenclature of [Topic]-algorithm.txt

**Pull request merged**
