### PR TITLE
floyd_cycle code added

### PR DESCRIPTION
**Pull request by gayatri517**
Solution to issue: #34 
For Hacktoberfest 2021

### CODE REVIEW

**Comment by gayatri517** [comment]
@Sushreesatarupa Kindly add the hacktoberfest accepted label to this PR

**Comment by gayatri517** [comment]
@Sushreesatarupa Kindly add the hacktoberfest accepted label to this PR

**Comment by gayatri517** [comment]
@Sayansree @Dibyansika @Sushreesatarupa Kindly add the hacktoberfest accepted label to this PR

**Comment by Sushreesatarupa** [comment]
Hacktoberfest has excluded all the repositories related to data structures
and algorithms, problem solving, algorithms solving to reduce spamy
contributions and increase the quality of pull requests!

**Pull request merged**
